<?php

/**
 * @file
 * Hooks for install and uninstall.
 */

use Drupal\Core\File\FileSystemInterface;

/**
 * Implements hook_install().
 */
function bunny_stream_install($is_syncing): void {

  $path = \Drupal::service('extension.list.module')->getPath('bunny_stream') . '/images/icon/no-thumbnail.png';

  /** @var \Drupal\Core\File\FileSystemInterface $fileSystem */
  $fileSystem = \Drupal::service('file_system');

  $directory = 'public://bunny_stream_thumbnails/';

  $fileSystem->prepareDirectory($directory, FileSystemInterface::CREATE_DIRECTORY | FileSystemInterface::MODIFY_PERMISSIONS);

  $fileSystem->copy($path, $directory . 'bunny-thumbnail.png');
}
