bunny_stream.bunny_stream_library.*:
  type: config_entity
  label: Bunny Stream Library
  mapping:
    id:
      type: machine_name
      label: Library ID
    label:
      type: label
      label: Label
    description:
      type: text
      label: 'Description'
    api_key:
      type: string
      label: Api Key
      constraints:
        Uuid:
          versions: 4
    cdn_hostname:
      type: string
      label: CDN Hostname
      constraints:
        NotBlank: []
    pull_zone:
      type: label
      label: Pull Zone
    token_authentication_key:
      type: string
      label: Token Authentication Key
      constraints:
        Uuid:
          versions: 4

field.formatter.settings.bunny_stream_embed:
  type: mapping
  label: Bunny Stream formatter settings
  mapping:
    responsive:
      type: boolean
      label: Responsive
    autoplay:
      type: boolean
      label: Autoplay
    preload:
      type: boolean
      label: Preload
    loop:
      type: boolean
      label: Loop
    muted:
      type: boolean
      label: Muted
    allow_fullscreen:
      type: boolean
      label: Allow fullscreen
    time:
      type: integer
      label: 'Token expiration time'

media.source.bunny_stream:
  type: media.source.field_aware
  label: 'Bunny Stream media source configuration'
  mapping:
    thumbnails_directory:
      type: uri
      label: 'URI of thumbnail storage directory'
    library:
      type: string
      label: 'Bunny Stream library ID'

# Schema for the configuration files of the Bunny Stream module.
bunny_stream.settings:
  type: config_object
  label: 'Bunny Stream settings'
  mapping:
    webhook_hash:
      type: string
      label: 'Webhook hash'
