bunny_stream.bunny_stream_library.*:
  type: config_entity
  label: Bunny Stream Library
  mapping:
    id:
      type: machine_name
      label: Library ID
    label:
      type: label
      label: Label
    description:
      type: text
      label: 'Description'
    allow_upload:
      type: boolean
      label: 'Allow video uploads'
    api_key:
      type: string
      label: Api Key
      nullable: true
      constraints:
        Uuid:
          versions: 4
    cdn_hostname:
      type: string
      label: CDN Hostname
      constraints:
        NotBlank: []
    pull_zone:
      type: label
      label: Pull Zone
    token_authentication_key:
      type: string
      label: Token Authentication Key
      constraints:
        Uuid:
          versions: 4
    read_only_api_key:
      type: string
      label: Read-only API key
      nullable: true
      constraints:
        Uuid:
          versions: 4

field.formatter.settings.bunny_stream_embed:
  type: mapping
  label: Bunny Stream formatter settings
  mapping:
    responsive:
      type: boolean
      label: Responsive
    autoplay:
      type: boolean
      label: Autoplay
    preload:
      type: boolean
      label: Preload
    loop:
      type: boolean
      label: Loop
    muted:
      type: boolean
      label: Muted
    allow_fullscreen:
      type: boolean
      label: Allow fullscreen
    time:
      type: integer
      label: 'Token expiration time'

media.source.bunny_stream:
  type: media.source.field_aware
  label: 'Bunny Stream media source configuration'
  mapping:
    thumbnails_directory:
      type: uri
      label: 'URI of thumbnail storage directory'
    library:
      type: string
      label: 'Bunny Stream library ID'

field.widget.settings.bunny_stream_textfield:
  type: mapping
  label: 'Bunny Stream widget settings'
  mapping:
    mode:
      type: string
      label: 'Widget mode for new media'
      constraints:
        Choice:
          - upload
          - existing

field.storage_settings.bunny_stream_video:
  type: field.storage_settings.string
  label: 'Bunny Stream video storage settings'

field.value.bunny_stream_video:
  type: mapping
  label: 'Default value'
  mapping:
    value:
      type: string
      label: 'Video ID'
    width:
      type: integer
      label: 'Width'
      nullable: true
    height:
      type: integer
      label: 'Height'
      nullable: true
